-- AlterEnum
ALTER TYPE "EquipmentStatus" ADD VALUE 'RESERVED';

-- AlterTable
ALTER TABLE "Checkout" ADD COLUMN     "reservedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "checkedOutAt" DROP NOT NULL,
ALTER COLUMN "checkedOutAt" DROP DEFAULT;
