-- AlterTable
ALTER TABLE "Payment" ADD COLUMN     "tipAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tipToBusinessAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "PaymentSplit" ADD COLUMN     "tipAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

