-- Convert PaymentMethod enum columns to plain TEXT. Payment methods are now
-- fully configuration-driven via the PAYMENT_METHODS setting (JSON taxonomy);
-- the DB enum is dropped so adding a new method is a pure Settings edit.
--
-- In-place type conversion with USING — existing enum values cast to their
-- text representation verbatim ('VENMO' stays 'VENMO'). No data loss, no
-- backfill. (Prisma's autogenerated DROP/ADD COLUMN was replaced with this.)

-- AlterTable: Payment.method enum -> TEXT
ALTER TABLE "Payment"
  ALTER COLUMN "method" TYPE TEXT USING "method"::text;

-- AlterTable: ClientContact.preferredPaymentMethod enum -> TEXT
ALTER TABLE "ClientContact"
  ALTER COLUMN "preferredPaymentMethod" TYPE TEXT USING "preferredPaymentMethod"::text;

-- DropEnum: no longer referenced by any column
DROP TYPE "public"."PaymentMethod";
