
name: deploy-api
on:
  push:
    branches: [ main ]
    paths:
      - "apps/api/**"
      - "packages/**"
      - ".github/workflows/deploy-api.yml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root deps
        run: npm install

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push Image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/hello-api:${{ github.sha }}
          gcloud builds submit apps/api --tag $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-api             --image $IMAGE             --platform managed             --region ${{ secrets.GCP_REGION }}             --allow-unauthenticated             --port 8080             --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }},CLERK_JWT_VERIFICATION_KEY=${{ secrets.CLERK_JWT_VERIFICATION_KEY }}"

      - name: Run DB migrations
        run: |
          docker run --rm             -e DATABASE_URL=${{ secrets.DATABASE_URL }}             $IMAGE npm run migrate:deploy
