name: deploy-api

on:
  push:
    branches: [main]
    paths:
      - "apps/api/**"
      - "packages/**"
      - ".github/workflows/deploy-api.yml"
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: gcloud config set project ${{ secrets.GCP_PROJECT }}

      # Configure Docker to push to Artifact Registry in your region
      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      # Build & push container directly from the runner (no Cloud Build, no _cloudbuild bucket)
      - name: Build & Push Image (local build)
        run: |
          IMAGE=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/seedlings3-api/seedlings3-api:${{ github.sha }}
          docker build -t "$IMAGE" apps/api
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy seedlings3 \
            --image $IMAGE \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --port 8080 \
            --set-env-vars "DATABASE_URL=${{ secrets.DATABASE_URL }},CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }},CLERK_JWT_VERIFICATION_KEY=${{ secrets.CLERK_JWT_VERIFICATION_KEY }},WEB_ORIGIN=${{ secrets.WEB_ORIGIN }}"

      - name: Show Cloud Run URL
        run: |
          URL=$(gcloud run services describe seedlings3 --region ${{ secrets.GCP_REGION }} --format='value(status.url)')
          echo "CLOUD_RUN_URL=$URL"
          echo "CLOUD_RUN_URL=$URL" >> $GITHUB_ENV

      # Use the runner's Node/OS to run Prisma, not the container
      - name: Set up Node for migrations
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run DB migrations (on runner)
        working-directory: apps/api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm install
          npx prisma generate
          npx prisma migrate deploy --schema prisma/schema.prisma
